version: "3.8"

services:
  doomcoin:
    build: .
    container_name: doomcoin-node
    restart: unless-stopped
    ports:
      - "3333:3333"
      - "3334:3334"
    volumes:
      - ./data:/data
    environment:
      - RPC_PASSWORD=CHANGE_ME
    command: >
      bitcoind
      -conf=/etc/doomcoin/doomcoin.conf
      -datadir=/data
      -printtoconsole
      -server=1
